<?php

namespace MQVBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CavisteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CavisteRepository extends EntityRepository
{
}
