<?php

namespace MQVBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RecetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecetteRepository extends EntityRepository
{
}
