<?php

namespace MQVBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VentesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VentesRepository extends EntityRepository
{
}
